# AI 산업 전반 + Frontier AI Lab 모니터링용 RSS 피드 목록
# last_updated: 2025-08-16

feeds:
  # --- Frontier / Big Tech Labs & Research ---
  - name: Official OpenAI Blog RSS
    url: https://openai.com/blog/rss.xml
    group: frontier_lab
  - name: Google AI Blog
    url: https://ai.googleblog.com/feeds/posts/default?alt=rss
    group: frontier_lab
  - name: Google Blog (AI Category)
    url: https://blog.google/technology/ai/rss/
    group: frontier_lab
  - name: Google DeepMind (Legacy Blog Feed)
    url: https://deepmind.com/blog/feed/basic/
    group: frontier_lab
  - name: Microsoft Research Blog
    url: https://www.microsoft.com/en-us/research/blog/feed/
    group: frontier_lab
  - name: NVIDIA Developer Blog
    url: https://developer.nvidia.com/blog/feed
    group: industry
  - name: NVIDIA Newsroom
    url: https://nvidianews.nvidia.com/rss
    group: industry
  - name: Hugging Face Blog
    url: https://huggingface.co/blog/feed.xml
    group: ecosystem
  - name: Meta Engineering (엔지니어링 블로그)
    url: https://engineering.fb.com/feed/
    group: industry
  - name: Stability AI Blog
    url: https://stability.ai/blog?format=rss
    group: frontier_lab
  # 2025-08-20 추가
  - name: Anthropic News  # 비공식 RSS 미러
    url: https://raw.githubusercontent.com/Olshansk/rss-feeds/main/anthropic.com/news.rss
    group: frontier_lab
  - name: Cohere Blog
    url: https://cohere.com/blog/rss
    group: frontier_lab
  - name: Mistral AI News
    url: https://mistral.ai/news/rss
    group: frontier_lab
  - name: IBM Research Blog
    url: https://research.ibm.com/blog/rss
  - name: Apple Machine Learning Research
    url: https://machinelearning.apple.com/feed.xml
    group: frontier_lab

  # --- Frontier Lab Korea
  - name: Naver Labs Blog
    url: https://www.naverlabs.com/blog/feed
    group: frontier_lab_korea
  - name:  Kakao AI Blog
    url: https://medium.com/kakao-ai/feed
    group: frontier_lab_korea
  - name: Samsung Global Newsroom - AI Category
    url: https://news.samsung.com/global/category/technology/artificial-intelligence/feed
    group: frontier_lab_korea
  - name: LG AI Research Blog
    url: https://www.lgresearch.ai/blog/feed
    group: frontier_lab_korea
  - name: Upstage AI Blog
    url: https://upstage.ai/blog/feed
    group: frontier_lab_korea

  # --- Academic / Research Labs ---
  - name: BAIR (Berkeley AI Research) Blog
    url: https://bair.berkeley.edu/blog/feed.xml
    group: academia
  - name: ML@CMU Blog
    url: https://blog.ml.cmu.edu/feed/
    group: academia
  - name: Stanford SAIL Blog
    url: http://ai.stanford.edu/blog/feed.xml
    group: academia
  - name: EleutherAI Blog
    url: https://blog.eleuther.ai/index.xml
    group: open_research
  # 2025-08-20 추가
  - name: MIT CSAIL News
    url: https://www.csail.mit.edu/news/rss.xml
    group: academia
  - name: AI Alignment Forum
    url: https://www.alignmentforum.org/rss
    group: open_research

  # --- (Korea) Academic / Research Labs ---
  - name: KAIST Graduate School of AI Blog
    url: https://gsai.kaist.ac.kr/blog/feed
    group: academia_korea
  - name: SNU AI Institute Blog
    url: https://medium.com/snu-aiis-blog/feed
    group: academia_korea
  - name: ETRI Jounral RSS
    url: https://onlinelibrary.wiley.com/rss/journal/22337326
    group: academia_korea

  # --- Cloud & Platform AI ---
  - name: AWS Machine Learning Blog
    url: https://aws.amazon.com/blogs/machine-learning/feed/
    group: cloud_ai
  - name: Google Cloud Blog (전체 피드)
    url: https://blog.google/feed/
    group: cloud_ai

  # --- Research Paper Streams (arXiv) ---
  - name: arXiv cs.AI
    url: https://export.arxiv.org/rss/cs.AI
    group: arxiv
  - name: arXiv cs.LG (ML)
    url: https://export.arxiv.org/rss/cs.LG
    group: arxiv
  - name: arXiv cs.CL (NLP)
    url: https://export.arxiv.org/rss/cs.CL
    group: arxiv
  - name: arXiv stat.ML
    url: https://export.arxiv.org/rss/stat.ML
    group: arxiv

  # --- Media / Aggregators (신뢰성 편차 있음) ---
  - name: The Gradient
    url: https://thegradient.pub/rss/
    group: media
  - name: MarkTechPost (AI 뉴스)
    url: https://www.marktechpost.com/feed
    group: media
  - name: THE DECODER (AI 뉴스)
    url: https://the-decoder.com/feed/
    group: media
  - name: TechCrunch – AI 카테고리
    url: https://techcrunch.com/category/artificial-intelligence/feed/
    group: media
  # 2025-08-20 추가
  - name: VentureBeat AI Category
    url: https://venturebeat.com/category/ai/feed
    group: media
  - name: Wired AI Tag
    url: https://www.wired.com/tag/artificial-intelligence/rss
    group: media
  - name: Towards Data Science
    url: https://towardsdatascience.com/feed
    group: media

  # --- Legacy Feeds (기존 get_rss_feeds.py에서 변환) ---
  # Machine Learning
  - name: Cube_dev
    url: https://blog.statsbot.co/rss
    group: legacy_ml
  - name: Machine_Learning_Mastery
    url: https://machinelearningmastery.com/feed/
    group: legacy_ml
  - name: ML_Uber_Engineering
    url: https://eng.uber.com/feed/
    group: legacy_ml
  - name: ML_Reddit
    url: https://www.reddit.com/r/MachineLearning/.rss
    group: legacy_ml
  - name: ML_in_production
    url: https://mlinproduction.com/feed/
    group: legacy_ml
  - name: Jay_Alammar_blog
    url: http://jalammar.github.io/feed.xml
    group: legacy_ml
  - name: JMLR_recent_papers
    url: http://www.jmlr.org/jmlr.xml
    group: legacy_ml
  - name: Distill_blog
    url: https://distill.pub/rss.xml
    group: legacy_ml
  - name: inFERENCe_blog
    url: https://www.inference.vc/feed/
    group: legacy_ml

  # Artificial Intelligence
  - name: AI_Trends
    url: https://www.aitrends.com/feed/
    group: legacy_ai
  - name: AI_Weirdness
    url: https://aiweirdness.com/feed
    group: legacy_ai
  - name: Becoming_Human
    url: https://becominghuman.ai/feed
    group: legacy_ai
  - name: MIT_AI_News
    url: http://news.mit.edu/rss/topic/artificial-intelligence2
    group: legacy_ai
  - name: David_Stutz_AI_Paper_Review
    url: https://davidstutz.de/feed/
    group: legacy_ai
  - name: AI_Reddit
    url: https://www.reddit.com/r/artificial/.rss
    group: legacy_ai
  - name: Reddit_NN_DL
    url: https://www.reddit.com/r/neuralnetworks/.rss
    group: legacy_ai
  - name: ScienceDaily_AI
    url: https://www.sciencedaily.com/rss/computers_ai.xml
    group: legacy_ai
  - name: Daniel_Takeshi_Blog
    url: https://danieltakeshi.github.io/feed.xml
    group: legacy_ai
  - name: Vitalab_LitReview
    url: https://vitalab.github.io/feed.xml
    group: legacy_ai
  - name: Andrej_Karpathy
    url: https://karpathy.medium.com/feed
    group: legacy_ai
  - name: FastAI_Blog
    url: http://www.fast.ai/feeds/blog.xml
    group: legacy_ai

  # Reinforcement Learning
  - name: RL_Reddit
    url: https://www.reddit.com/r/reinforcementlearning/.rss
    group: legacy_rl
  - name: RL_Weekly
    url: https://www.getrevue.co/profile/seungjaeryanlee?format=rss
    group: legacy_rl
  - name: RL_Paper_Review
    url: https://dtransposed.github.io/feed.xml
    group: legacy_rl

  # Data Science
  - name: Data_Science_Central
    url: https://www.datasciencecentral.com/feed/
    group: legacy_ds
  - name: John_Cook_Blog
    url: https://www.johndcook.com/blog/feed/
    group: legacy_ds

